### ISSUE TITLE
allow copying direct url

### ISSUE THREAD

**Issue by ScDor** [Yharooer/panopto-downloader-chrome#2]
sometimes I like playing videos on VLC rather than downloading

I'd love it if there was some button to copy the direct video URL to the clipboard (next to "download")

thanks!

**Comment by Yharooer** [comment]
Thanks for your suggestion. I have chosen not to include this feature since most of the time the videos are only accessible when logged into an account with the necessary permissions. This means that the video will only be accessible through the browser you have logged in with and not with an external player like VLC. I think it would be misleading to give users the option to copy links if the links don't work in other programs.
